const cities = {
    "UA":"AB1",
    "CDE":"CI35",
    "ENC":"EN54",
    "PJC":"PE141",
    "SDG":"SA247",
    "Acahay":"AC222",
    "Alberdi":"AL2",
    "Alto Verá":"AL3",
    "Altos":"AL4",
    "Antequera":"AN5",
    "Aregua":"AR6",
    "Arroyos y Esteros":"AR7",
    "Asunción":"AS8",
    "Atyra":"AT9",
    "Ayolas":"AY10",
    "Azotey":"AZ251",
    "Bahía Negra":"BA11",
    "Belén":"BE12",
    "Bella Vista - Amambay":"BE13",
    "Bella Vista - Itapúa":"BE14",
    "Benjamín Aceval":"BE15",
    "Borja":"BO16",
    "Buena Vista":"BU17",
    "Caacupé":"CA18",
    "Caaguazú":"CA19",
    "Caapucú":"CA223",
    "Caazapá":"CA20",
    "Cambyretá":"CA21",
    "Capiatá":"CA24",
    "Capiibary":"CA23",
    "Capitán Bado":"CA25",
    "Capitán Carmelo Peralta":"CA22",
    "Capitán Mauricio José Troche":"CA26",
    "Capitán Meza":"CA27",
    "Capitán Miranda":"CA28",
    "Caraguatay":"CA29",
    "Carapeguá":"CA224",
    "Carayaó":"CA30",
    "Carlos Antonio López":"CA31",
    "Carmen del Paraná":"CA32",
    "Cerrito":"CE33",
    "Choré":"CH34",
    "Ciudad del Este":"CI35",
    "Colonia Fernheim":"CO36",
    "Concepción":"CO37",
    "Coronel Bogado":"CO38",
    "Coronel Martínez":"CO39",
    "Coronel Oviedo":"CO40",
    "Corpus Christi":"CO240",
    "Curuguaty":"CU241",
    "Desmochados":"DE41",
    "Domingo Martínez de Irala":"DO48",
    "Dr J. Eulogio Estigarribia":"DO44",
    "Dr Juan Manuel Frutos":"DO45",
    "Dr Moisés S. Bertoni":"DO46",
    "Dr Raúl Peña":"DO49",
    "Dr. Blás A. Garay":"DR49",
    "Dr. Botrell":"DO42",
    "Dr. Cecilio Baez":"DO43",
    "Dr. José Falcón":"DR50",
    "Dr. Juan León Mallorquín":"DR51",
    "Dr. Pedro P. Peña":"DO47",
    "Edelira":"ED52",
    "Emboscada":"EM53",
    "Encarnación":"EN54",
    "Escobar":"ES225",
    "Eusebio Ayala":"EU55",
    "Félix Pérez Cardozo":"FE56",
    "Fernando de la Mora":"FE57",
    "Filadelfia":"FI58",
    "Fn. Pozo Hondo PY":"FN59",
    "Fram":"FR60",
    "Fuerte Olimpo":"FU61",
    "Fulgencio Yegros":"FU62",
    "Garay":"GE70",
    "General":"GE64",
    "General Artigas":"GE66",
    "General Delgado":"GE67",
    "General Elizardo Aquino":"GE68",
    "General Eugenio A. Garay":"GE69",
    "General Higinio Morínigo":"GE71",
    "General Isidoro Resquín":"GE72",
    "General José Eduvigis Díaz":"GE74",
    "General José María Bruguez":"GE73",
    "Gral. Bernardino Caballero":"GE227",
    "Gral. Francisco Caballero Álvarez":"GR242",
    "Guarambaré":"GU75",
    "Guayaibí":"GU76",
    "Guazú Cuá":"GU77",
    "Hernandarias":"HE78",
    "Hohenau":"HO79",
    "Horqueta":"HO80",
    "Humaitá":"HU81",
    "Independencia":"IN82",
    "Iruña":"IR83",
    "Isla Pucú":"IS84",
    "Isla Umbú":"IS85",
    "Itá":"IT86",
    "Itacurubí de La Cordillera":"IT87",
    "Itacurubí del Rosario":"IT88",
    "Itakyry":"IT89",
    "Itanará":"IT243",
    "Itapé":"IT90",
    "Itapúa Poty":"IT91",
    "Itauguá":"IT92",
    "Iturbe":"IT93",
    "Jesús":"JE94",
    "Jose A. Fassardi":"JO95",
    "José Domingo Ocampos":"JO96",
    "José Leandro Oviedo":"JO97",
    "Juan de Mena":"JU99",
    "Juan Emilio O'Leary":"JU100",
    "Julian Augusto Saldiviar":"JU98",
    "Katueté":"KA244",
    "La Colmena":"LA228",
    "La Paloma":"LA245",
    "La Pastora":"LA101",
    "La Paz":"LA102",
    "Lambaré":"LA103",
    "Laureles":"LA104",
    "Liberación":"LI105",
    "Lima":"LI106",
    "Limpio":"LI107",
    "Loma Grande":"LO108",
    "Loma Plata":"LO109",
    "Loreto":"LO110",
    "Los Cedrales":"LO111",
    "Luque":"LU112",
    "Maciel":"MA113",
    "Mariano Roque Alonso":"MA114",
    "Mariscal Estigarribia":"MA116",
    "Mayor José J. Martínez":"MA117",
    "Mayor Otaño":"MA118",
    "Mayor Pablo Lagerenza":"MA119",
    "Mbaracayú":"MB120",
    "Mbocayaty":"MB121",
    "Mbocayaty del Yhaguy":"MB122",
    "Mbuyapey":"MB229",
    "Mcal. Francisco S. López":"MA115",
    "Minga Guazú":"MI123",
    "Minga Porá":"MI124",
    "Nanawa":"NA126",
    "Naranjal":"NA127",
    "Natalicio Talavera":"NA128",
    "Natalio":"NA129",
    "Neuland":"NE131",
    "Nueva Alborada":"NU132",
    "Nueva Colombia":"NU133",
    "Nueva Esperanza":"NU246",
    "Nueva Germania":"NU134",
    "Nueva Italia":"NU135",
    "Nueva Londres":"NU136",
    "Ñacunday":"NA125",
    "Ñemby":"NE130",
    "Ñumí":"NU137",
    "Obligado":"OB138",
    "Paraguarí":"PA230",
    "Paso de Patria":"PA139",
    "Paso Yobái":"PA140",
    "Pedro Juan Caballero":"PE141",
    "Pilar":"PI142",
    "Pirapó":"PI143",
    "Pirayú":"PI231",
    "Piribebuy":"PI144",
    "Pozo Colorado":"PO145",
    "Presidente Franco":"PR146",
    "Primero de Marzo":"PR147",
    "Puerto Casado":"PU148",
    "Puerto Pinasco":"PU149",
    "Quiindy":"QU232",
    "Quyquyhó":"QU233",
    "R. I. Tres Corrales":"R.150",
    "Raúl Arsenio Oviedo":"RA151",
    "Repatriación":"RE152",
    "Salto del Guairá":"SA247",
    "San Alberto":"SA153",
    "San Antonio":"SA154",
    "San Bernardino":"SA155",
    "San Carlos del Apa":"SA156",
    "San Cosme y Damián":"SA157",
    "San Cristóbal":"SA158",
    "San Estanislao":"SA159",
    "San Ignacio":"SA160",
    "San Joaquín":"SA161",
    "San José de los Arroyos":"SA162",
    "San José Obrero":"SA163",
    "San Juan Bautista":"SA165",
    "San Juan Bautista del Neembucú":"SA164",
    "San Juan del Paraná":"SA166",
    "San Juan Nepomuceno":"SA167",
    "San Lázaro":"SA168",
    "San Lorenzo":"SA169",
    "San Miguel":"SA170",
    "San Pablo":"SA171",
    "San Patricio":"SA172",
    "San Pedro":"SA173",
    "San Pedro del Paraná":"SA174",
    "San Rafael del Paraná":"SA175",
    "San Roque González de Santa Cruz":"SA234",
    "San Salvador":"SA176",
    "Santa Elena":"SA177",
    "Santa Fe del Paraná":"SA178",
    "Santa María":"SA179",
    "Santa Rita":"SA180",
    "Santa Rosa":"SA181",
    "Santa Rosa del Aguaray":"SA182",
    "Santa Rosa del Mbutuy":"SA183",
    "Santa Rosa del Monday":"SA184",
    "Santiago":"SA185",
    "Sapucai":"SA235",
    "Sargento José Félix López":"SA252",
    "Simón Bolívar":"SI186",
    "Tacuaras":"TA187",
    "Tacuatí":"TA188",
    "Tavaí":"TA189",
    "Tavapy":"TA253",
    "Tebicuary":"TE190",
    "Tebicuary-mí":"TE236",
    "Tembiaporá":"TE191",
    "Tobatí":"TO192",
    "Tomás Romero Pereira":"TO193",
    "Tres de Febrero":"TR194",
    "Trinidad":"TR195",
    "Tte. Esteban Martínez":"TT197",
    "Tte. Irala Fernández":"TT196",
    "Unión":"UN198",
    "Valenzuela":"VA199",
    "Vaquería":"VA200",
    "Veinticinco de Diciembre":"VE201",
    "Villa del Rosario":"VI202",
    "Villa Elisa":"VI203",
    "Villa Florida":"VI204",
    "Villa Franca":"VI205",
    "Villa Hayes":"VI206",
    "Villa Oliva":"VI207",
    "Villa Ygatimí":"VI248",
    "Villalbín":"VI208",
    "Villarrica":"VI209",
    "Villeta":"VI210",
    "Yabebyry":"YA211",
    "Yaguarón":"YA237",
    "Yasy Cañy":"YA249",
    "Yataity":"Yata-PY-4",
    "Yataity del Guairá":"YA212",
    "Yataity del Norte":"YA213",
    "Yatytay":"YA214",
    "Yby Yaú":"YB215",
    "Ybycuí":"YB238",
    "Ybytymí":"YB239",
    "Yguazú":"YG216",
    "Yhú":"YH217",
    "Ypacaraí":"YP218",
    "Ypané":"YP219",
    "Ypejhú":"YP250",
    "Yrybucuá":"YR220",
    "Yuti":"YU221",
    "Zanja Pytá":"ZA254"
};

export default function handler(req, res) {
    res.status(200).json(cities);
  }